#!/bin/bash

# 列出所有要创建的目录和文件
entries=(
  "frontend/public/index.html"
  "frontend/public/favicon.ico"
  "frontend/src/components/Layout/Header.tsx"
  "frontend/src/components/Layout/Sidebar.tsx"
  "frontend/src/components/Layout/index.tsx"
  "frontend/src/components/QuestionEditor/QuestionForm.tsx"
  "frontend/src/components/QuestionEditor/QuestionList.tsx"
  "frontend/src/components/QuestionEditor/index.tsx"
  "frontend/src/components/QuestionPreview/QuizInterface.tsx"
  "frontend/src/components/QuestionPreview/ResultDisplay.tsx"
  "frontend/src/components/QuestionPreview/index.tsx"
  "frontend/src/components/Common/Loading.tsx"
  "frontend/src/components/Common/ErrorBoundary.tsx"
  "frontend/src/components/Common/ConfirmDialog.tsx"
  "frontend/src/pages/Home/index.tsx"
  "frontend/src/pages/Dashboard/index.tsx"
  "frontend/src/pages/QuestionGenerator/index.tsx"
  "frontend/src/pages/Login/index.tsx"
  "frontend/src/pages/Register/index.tsx"
  "frontend/src/hooks/useAuth.ts"
  "frontend/src/hooks/useQuestions.ts"
  "frontend/src/hooks/useSocket.ts"
  "frontend/src/services/api.ts"
  "frontend/src/services/auth.ts"
  "frontend/src/services/questions.ts"
  "frontend/src/services/upload.ts"
  "frontend/src/store/authStore.ts"
  "frontend/src/store/questionStore.ts"
  "frontend/src/store/index.ts"
  "frontend/src/types/auth.ts"
  "frontend/src/types/question.ts"
  "frontend/src/types/api.ts"
  "frontend/src/utils/constants.ts"
  "frontend/src/utils/helpers.ts"
  "frontend/src/utils/validation.ts"
  "frontend/src/styles/globals.css"
  "frontend/src/styles/theme.ts"
  "frontend/src/App.tsx"
  "frontend/src/main.tsx"
  "frontend/src/vite-env.d.ts"
  "frontend/.env"
  "backend/src/controllers/authController.ts"
  "backend/src/controllers/questionController.ts"
  "backend/src/controllers/uploadController.ts"
  "backend/src/controllers/aiController.ts"
  "backend/src/middleware/auth.ts"
  "backend/src/middleware/errorHandler.ts"
  "backend/src/middleware/rateLimiter.ts"
  "backend/src/middleware/validation.ts"
  "backend/src/models/User.ts"
  "backend/src/models/Question.ts"
  "backend/src/models/Exercise.ts"
  "backend/src/models/Document.ts"
  "backend/src/routes/auth.ts"
  "backend/src/routes/questions.ts"
  "backend/src/routes/upload.ts"
  "backend/src/routes/ai.ts"
  "backend/src/services/aiService.ts"
  "backend/src/services/documentService.ts"
  "backend/src/services/questionService.ts"
  "backend/src/services/authService.ts"
  "backend/src/utils/database.ts"
  "backend/src/utils/redis.ts"
  "backend/src/utils/jwt.ts"
  "backend/src/utils/fileProcessor.ts"
  "backend/src/types/user.ts"
  "backend/src/types/question.ts"
  "backend/src/types/api.ts"
  "backend/src/config/database.ts"
  "backend/src/config/redis.ts"
  "backend/src/config/openai.ts"
  "backend/src/app.ts"
  "backend/src/server.ts"
  "backend/uploads/.gitkeep"
  "backend/.env"
  ".gitignore"
  "README.md"
  "docker-compose.yml"
)

# 创建每个目录和空文件
for entry in "${entries[@]}"; do
  dir=$(dirname "$entry")
  mkdir -p "$dir"
  touch "$entry"
done

echo "✅ 项目结构已创建完毕"